blog/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r"^blogs/$", views.BlogListView.as_view(), name="blogs"),
    url(r"^blogs/(?P<pk>[0-9]+)$", views.BlogDetailView.as_view(), name="blog-detail"),
    url(r"^bloggers/$", views.BlogAuthorListView.as_view(), name="bloggers"),
    url(r"^bloggers/(?P<pk>[0-9]+)$", views.BlogListbyAuthorView.as_view(), name="blogger-detail"),
    url(r"^(?P<pk>[0-9]+)/create/$", views.BlogCommentCreate.as_view(), name="create-comment"),
    url(r"^comment/(?P<pk>[0-9]+)/delete/$", views.BlogCommentDelete.as_view(), name="delete-comment"),
    url(r"^blog/(?P<pk>[0-9]+)/update/$", views.BlogUpdate.as_view(), name="update-blog"),
    url(r"^blog/(?P<pk>[0-9]+)/delete/$", views.BlogDelete.as_view(), name="delete-blog"),
    url(r"^bloggers/(?P<pk>[0-9]+)/update/$", views.BlogAuthorUpdate.as_view(), name="update-blogauthor"),
    url(r"^profilpage/$", views.ProfilPageListView.as_view(), name="profpage-user"),
    url(r"^newblogs/$", views.SeeNewBlogsListView.as_view(), name="new-blogs"),
    url(r"^blog/create/$", views.BlogCreate.as_view(), name="create-blog"),
    url(r'^signup/$', views.signup, name='signup'),

]

djblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url



urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='blog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User #Blog author or commenter
from datetime import date


class BlogAuthor(models.Model):
    """
    Model representing a blogger.
    """
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Enter your bio details here.", blank=True)
    prof_picture = models.ImageField(upload_to ='pp_pics/', height_field=None, width_field=None, default="default.jpg")

    class Meta:
        ordering = ["user","bio"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog-author instance.
        """
        return reverse('blogger-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.user.username


class Blog(models.Model):
    """
    Model representing a blog post.
    """
    name = models.CharField(max_length=200)
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because Blog can only have one author/User, but bloggsers can have multiple blog posts.
    description = models.TextField(max_length=2000, help_text="Enter you blog text here.")
    post_date = models.DateField(auto_now_add=True)
    
    class Meta:
        ordering = ["-post_date"]
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-detail', kwargs={'pk': self.pk})

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name
        
        
class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because BlogComment can only have one author/User, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title=75
        if len(self.description)>len_title:
            titlestring=self.description[:len_title] + '...'
        else:
            titlestring=self.description
        return titlestring

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.http import Http404


from .models import BlogComment, Blog, BlogAuthor
import datetime
#libraries for signup
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm





# Create your views here.

#signup view
def signup(request):
    """
    view that signes user up and creates a BlogAuthor object for the user
    """
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            #add BlogAuthor of user
            new_blogauthor = BlogAuthor(user=user)
            new_blogauthor.save()
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def index(request):
    num_blogs = Blog.objects.all().count()

    context = {
        "num_blogs": num_blogs,
    }

    return render(request, 'index.html', context=context)


class BlogListView(LoginRequiredMixin, generic.ListView):
    """
    generic class-based view for a list of blogs
    """
    model = Blog

class BlogDetailView(LoginRequiredMixin, generic.DetailView):
    """
    Generic class-based view for a detailed description of a blog
    """
    model = Blog

class BlogAuthorListView(LoginRequiredMixin, generic.ListView):
    model = BlogAuthor

class BlogListbyAuthorView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view for a list of blogs posted by a particular BlogAuthor.
    """
    model = Blog
    template_name ='blog/blog_list_by_author.html'
    
    def get_queryset(self):
        """
        Return list of Blog objects created by BlogAuthor (author id specified in URL)
        """
        try:
            id = self.kwargs['pk']
            target_author=get_object_or_404(BlogAuthor, pk = id)
            return Blog.objects.filter(author=target_author)
        except MyModel.DoesNotExist:
            raise Http404("No MyModel matches the given query.")

    def get_context_data(self, **kwargs):
        """
        Add BlogAuthor to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(BlogListbyAuthorView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['blogger'] = get_object_or_404(BlogAuthor, pk = self.kwargs['pk'])
        context["height"] = "200px"
        context["width"] = "200px"
        return context


class BlogCommentCreate(LoginRequiredMixin, CreateView):
    """
    Generic edit view used to Create comments
    """
    model = BlogComment
    fields = ['description',]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        context["blog"] = get_object_or_404(Blog, pk=self.kwargs['pk']) 
        return context
        
    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.author = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self):
        """
        After posting comment return to blog page
        """
        return reverse("blog-detail", kwargs={'pk': self.kwargs['pk'],})

class BlogCreate(LoginRequiredMixin, CreateView):
    """
    Generic edit class-based view to create Blogs
    """
    model = Blog
    fields = ["name", "description"]
    success_url = reverse_lazy('blogs')

    def form_valid(self, form):
        #take logged-in user as BlogAuthor and add it as Blogauthor to blog
        blog_author = BlogAuthor.objects.get(user=self.request.user)
        form.instance.author = blog_author
        # Call super-class form validation behaviour
        return super(BlogCreate, self).form_valid(form)
    

class BlogCommentDelete(LoginRequiredMixin, DeleteView):
    """
    Generic edit view used to delete comments
    """
    model = BlogComment

    def get_success_url(self):
        """
        When deleting the comments is successful return the user to url written below
        """
        return reverse("blog-detail", kwargs={'pk': self.kwargs['pk'],})

class BlogUpdate(LoginRequiredMixin, UpdateView):
    """
    Generic edit view used to update blogs
    """
    model = Blog
    fields = ['name', 'description']

    success_url = reverse_lazy("blogs")


class BlogDelete(LoginRequiredMixin, DeleteView):
    """
    Generic edit view used to delete blogs
    """
    model = Blog
    success_url = reverse_lazy("blogs")

class BlogAuthorUpdate(LoginRequiredMixin, UpdateView):
    """
    Generic edit view used to update BlogAuthors
    """
    model = BlogAuthor
    fields = ['bio', 'prof_picture']

    success_url = reverse_lazy("profpage-user")


class ProfilPageListView(LoginRequiredMixin, generic.ListView):
    """
    generic class-based view for the users BlogAuthor data
    """

    model = Blog
    template_name = "blog/profil_page_by_user.html"

    def get_queryset(self):
        """
        get queryset of blogs that are written by the logged in user
        """
        try:
            blog_author = BlogAuthor.objects.get(user = self.request.user)
            return Blog.objects.filter(author=blog_author)
        except MyModel.DoesNotExist:
            raise Http404("No MyModel matches the given query.")

    def get_context_data(self):
        """
        add data of user that is loged in to context variable
        """
        context = super(ProfilPageListView, self).get_context_data()
        context["blogger"] = BlogAuthor.objects.get(user=self.request.user)
        # authors = BlogAuthor.objects.get(user=self.request.user)
        context["num_blogs_user"] = Blog.objects.filter(author__user=self.request.user).count()
        return context

class SeeNewBlogsListView(LoginRequiredMixin, generic.ListView):
    """
    Generic edit class-based view for a list of Blogs written in a maximal time ago from the current time(logged in users blog excluded)
    """
    
    model = Blog
    template_name = "blog/see_new_blog.html"

    def get_queryset(self):
        """
        Add queryset of blogs written a maximum of 24h ago
        """
        try:
            return Blog.objects.all().exclude(author__user=self.request.user).filter(post_date__gte = datetime.date.today() - datetime.timedelta(hours=24))
        except MyModel.DoesNotExist:
            raise Http404("No MyModel matches the given query.")

blog/templates/blog/blog_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Blog</h1>

<p>Are you sure you want to delete the Blog?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-outline-success" value="Yes, delete.">
</form>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1> {{blog.name}} </h1>
<hr>
<p class="mb-3"><strong>Post date: </strong> {{blog.post_date}} </p>
<p class="mb-3"><strong>Author: </strong> <a href="{{blog.author.get_absolute_url}}">{{blog.author}}</a> </p>
<p class="mb-1"><strong>Description:</strong></p>
<p> {{blog.description}} </p>

<section class="mt-5 ml-5">
    <h3>Comments</h3>
    {% for comment in blog.blogcomment_set.all %}
    <hr>
    <div><p>{{comment.author}} ({{comment.post_date}}) - {{comment.description}}{% if user.is_authenticated and comment.author|stringformat:"s" == user.username|stringformat:"s" %}  <a href="{% url 'delete-comment' comment.id %}" class="ml-5 d-inline"> Delete Comment </a> {% endif %} </p> </div>
    {% endfor %}
    {% if user.is_authenticated %}
    <!-- make option to delete comment -->
    <a href="{% url 'create-comment' blog.id %}">Add a new comment</a></p>
    {% endif %}
</section>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Create/Update Blog</h1>
    <form action='' method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" vlaue="Submit" class="btn btn-outline-success">
    </form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 class="text-center">All blogs</h1>
        <section class="mt-5">
            <ul>
                {% for blog in blog_list %}
                    <li><a href=" {{ blog.get_absolute_url }} "> {{blog.name}} </a> ( {{blog.post_date}} ) -- <a href="{{blog.author.get_absolute_url}}">{{blog.author}}</a> {% if user.is_authenticated and blog.author|stringformat:"s" == user.username|stringformat:"s" %}  <p class="ml-5 d-inline"><a href="{% url 'update-blog' blog.pk %}"> Update Blog </a> - <a href="{% url 'delete-blog' blog.pk %}">Delete Blog</a> </p> {% endif %}</li>
                    {% if not forloop.last %} <hr> {% endif %}
                {% endfor %}
            </ul>    
        </section>
            
    

{% endblock %}

blog/templates/blog/blog_list_by_author.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="header">
        <img class="img-profpic" src="{{blogger.prof_picture.url}}" alt="alt">
        <h1 class="inline"> Blogger: {{blogger.user}} </h1>       
    </div>
    <section class="mt-4">
        <h3>Bio</h3>
        <i>{{blogger.bio}}</i>
    </section>
    <section class="mt-4">
        <h3>Blogs list</h3>
        <ul>
            {% for blog in blog_list %}
                <li><a href="{{blog.get_absolute_url}}">{{blog.name}}</a></li>
            {% endfor %}
        </ul>
    </section>

    
{% endblock %}

blog/templates/blog/blogauthor_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Update Bio</h1>

    <form action='' method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" class="btn btn-success mt-3">
    </form>
{% endblock %}

blog/templates/blog/blogauthor_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1 class="text-center">All Bloggers</h1>
<hr>    
<section class="mt-5">
    <ul>
        {% for blogger in blogauthor_list %}
           <li><a href="{{blogger.get_absolute_url}}">{{blogger.user}}</a></li> 
        {% endfor %}
    </ul>
</section>

{% endblock %}

blog/templates/blog/blogcomment_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Comment</h1>

<p>Are you sure you want to delete the selected comment?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-outline-success" value="Yes, delete.">
</form>

{% endblock %}

blog/templates/blog/blogcomment_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog-detail' blog.pk %}">{{blog.name}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" class="btn btn-outline-success" value="Submit" />
    
</form>
{% endblock %}  

blog/templates/blog/profil_page_by_user.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="row">
        <div class="col-4 col-md-5 my-auto">
            <img class="img-profpic"  src="{{blogger.prof_picture.url}}" alt="alt" id="img-profilpage">
        </div>
        <div class="col-8 col-md-6 header1">
            <article class="pt-3">
                <h1 class="font-weight-light">{{user.username}}     <a class="btn btn-outline-success text-decoration-none" href="{% url 'update-blogauthor' blogger.pk%}">Update Bio</a></h1>                  
            </article>
            <article class="mt-3">
                <h4>{{num_blogs_user}} {% if num_blogs_user != 1 %} Blogs {% else %} Blog {% endif %}</h4>     
                
            </article>
        </div>
    </div>    
<section class="mt-5">
    <article class="">
        <h3>Bio:</h3>
        <p>{{blogger.bio}}</p>

    </article>
    
    <article class="mt-5">
        <h3>Your Blogs</h3>
        {% for blog in blog_list %} 
        <li><a href=" {{ blog.get_absolute_url }} "> {{blog.name}} </a> ( {{blog.post_date}} ) <p class="ml-5 d-inline"><a href="{% url 'update-blog' blog.pk %}"> Update Blog </a> - <a href="{% url 'delete-blog' blog.pk %}">Delete Blog</a> </p></li>
        {% if not forloop.last %} <hr> {% endif %}
        {% endfor %}
    </article>
</section>


{% endblock %}

blog/templates/blog/see_new_blog.html
{% extends "base_generic.html" %}

{% block content %}
<h1 class="text-center"> New Blogs</h1>

<section>
    <article>
        <ul>
            {% for blog in blog_list %}
            <li><a href="{{blog.get_absolute_url}}">{{blog.name}}</a> -- <a href="{{blog.author.get_absolute_url}}">{{blog.author}}</a> -- {{blog.post_date}} </li>
            {% if not forloop.last %}
            <hr>
            {% endif %}
            {% empty %}
            <h4 class="pt-5">There are no new blogs</h4>
            {% endfor %}
        </ul>
    </article>
</section>
{% endblock %}